// RAGFlow 双语文档清单——本文件由 scripts/ragflow-docs/gen-manifest.py 生成，勿手改。
// 数据源：scripts/ragflow-docs/manifest.py（单一事实源）+ en/ 目录的分片文件。
// 消费方：BilingualOverlay（头部标题/原文链接/上下篇导航）、RagflowDocLink（href）。
export interface RagflowDocMeta {
  slug: string      // 站内标识，对应 posts/ai/ragflow/paired/<slug>.md
  group: string     // 分组名（与官方文档板块结构一致）
  titleZh: string   // 中文标题（overlay 头部主标题）
  titleEn: string   // 英文标题（副标题）
  sourceUrl: string // 官方英文原文链接（「阅读原文」入口）
}

export const ragflowDocs: RagflowDocMeta[] = [
  { slug: 'quickstart', group: '快速开始', titleZh: '快速开始', titleEn: 'Quickstart', sourceUrl: 'https://ragflow.io/docs/' },
  { slug: 'basics-rag', group: '基础概念', titleZh: 'RAG 是什么？', titleEn: 'What Is Retrieval-Augmented Generation (RAG)?', sourceUrl: 'https://ragflow.io/docs/basics/rag' },
  { slug: 'basics-agent-context-engine', group: '基础概念', titleZh: 'Agent 上下文引擎是什么？', titleEn: 'What Is Agent Context Engine?', sourceUrl: 'https://ragflow.io/docs/basics/agent_context_engine' },
  { slug: 'guides-dataset-overview', group: '指南 · 数据集', titleZh: '数据集概览', titleEn: 'Dataset Overview', sourceUrl: 'https://ragflow.io/docs/guides/dataset/dataset_overview' },
  { slug: 'guides-dataset-list-creation', group: '指南 · 数据集', titleZh: '数据集列表与创建', titleEn: 'Dataset List and Creation', sourceUrl: 'https://ragflow.io/docs/guides/dataset/dataset_list_and_creation' },
  { slug: 'guides-dataset-configuration', group: '指南 · 数据集', titleZh: '数据集配置', titleEn: 'Dataset Configuration', sourceUrl: 'https://ragflow.io/docs/guides/dataset/configuration' },
  { slug: 'guides-dataset-files', group: '指南 · 数据集', titleZh: '文件：数据集文档管理', titleEn: 'Files: Dataset Document Management', sourceUrl: 'https://ragflow.io/docs/guides/dataset/files_dataset_document_management' },
  { slug: 'guides-dataset-retrieval-testing', group: '指南 · 数据集', titleZh: '检索测试', titleEn: 'Retrieval Testing', sourceUrl: 'https://ragflow.io/docs/guides/dataset/retrieval_testing' },
  { slug: 'guides-dataset-chunk-management', group: '指南 · 数据集', titleZh: '分块：解析结果与知识片段管理', titleEn: 'Chunk: Parsing Results and Knowledge Fragment Management', sourceUrl: 'https://ragflow.io/docs/guides/dataset/chunk_parsing_results_and_knowledge_fragment_management' },
  { slug: 'guides-dataset-metadata', group: '指南 · 数据集', titleZh: '元数据管理', titleEn: 'Metadata Management', sourceUrl: 'https://ragflow.io/docs/guides/dataset/metadata_management' },
  { slug: 'guides-dataset-logs', group: '指南 · 数据集', titleZh: '日志', titleEn: 'Logs', sourceUrl: 'https://ragflow.io/docs/guides/dataset/logs' },
  { slug: 'guides-dataset-notes-faqs', group: '指南 · 数据集', titleZh: '注意事项与常见问题', titleEn: 'Notes and FAQs', sourceUrl: 'https://ragflow.io/docs/guides/dataset/notes_and_faqs' },
  { slug: 'guides-dataset-artifacts', group: '指南 · 数据集', titleZh: '知识工件生成与管理', titleEn: 'Artifacts: Knowledge Artifact Generation and Management', sourceUrl: 'https://ragflow.io/docs/guides/dataset/artifacts_knowledge_artifact_generation_and_management' },
  { slug: 'guides-dataset-accelerate', group: '指南 · 数据集', titleZh: '最佳实践：加速索引', titleEn: 'Accelerate Indexing', sourceUrl: 'https://ragflow.io/docs/guides/dataset/best_practices/accelerate_doc_indexing' },
  { slug: 'guides-file-overview', group: '指南 · 文件', titleZh: '文件与文件夹', titleEn: 'Files and Folders', sourceUrl: 'https://ragflow.io/docs/guides/file/file' },
  { slug: 'guides-file-operations', group: '指南 · 文件', titleZh: '文件操作', titleEn: 'File Operations', sourceUrl: 'https://ragflow.io/docs/guides/file/file_operations' },
  { slug: 'guides-file-batch', group: '指南 · 文件', titleZh: '批量移动与删除', titleEn: 'Batch Move and Delete', sourceUrl: 'https://ragflow.io/docs/guides/file/batch_move_and_delete' },
  { slug: 'guides-file-link-dataset', group: '指南 · 文件', titleZh: '关联知识库', titleEn: 'Link Knowledge Base', sourceUrl: 'https://ragflow.io/docs/guides/file/link_dataset' },
  { slug: 'guides-data-source-overview', group: '指南 · 数据源', titleZh: '数据源概览与页面管理', titleEn: 'Data Source Overview and Page Management', sourceUrl: 'https://ragflow.io/docs/guides/data_source/overview_and_page_management' },
  { slug: 'guides-data-source-categories', group: '指南 · 数据源', titleZh: '数据源分类与选择', titleEn: 'Data Source Categories and Selection', sourceUrl: 'https://ragflow.io/docs/guides/data_source/data_source_categories_and_selection' },
  { slug: 'guides-data-source-configuration', group: '指南 · 数据源', titleZh: '数据源配置', titleEn: 'Data Source Configuration', sourceUrl: 'https://ragflow.io/docs/guides/data_source/data_source_configuration' },
  { slug: 'guides-data-source-sync', group: '指南 · 数据源', titleZh: '加入知识库并同步', titleEn: 'Add to Knowledge Base and Sync', sourceUrl: 'https://ragflow.io/docs/guides/data_source/add_to_knowledge_base_and_sync' },
  { slug: 'guides-chat-overview', group: '指南 · 对话', titleZh: '功能概览与创建', titleEn: 'Feature Overview and Creation', sourceUrl: 'https://ragflow.io/docs/guides/chat/feature_overview_and_creation' },
  { slug: 'guides-chat-configuration', group: '指南 · 对话', titleZh: '对话配置', titleEn: 'Chat Configuration', sourceUrl: 'https://ragflow.io/docs/guides/chat/chat_configuration' },
  { slug: 'guides-chat-sessions', group: '指南 · 对话', titleZh: '使用对话会话', titleEn: 'Using Chat Sessions', sourceUrl: 'https://ragflow.io/docs/guides/chat/using_chat_sessions' },
  { slug: 'guides-chat-multimodel-faq', group: '指南 · 对话', titleZh: '多模型对比', titleEn: 'Multi-model Comparison', sourceUrl: 'https://ragflow.io/docs/guides/chat/Mutimodel_comparison_and_FAQ' },
  { slug: 'guides-chatchannel-overview', group: '指南 · 对话渠道', titleZh: '对话渠道概览', titleEn: 'Chat Channels Overview', sourceUrl: 'https://ragflow.io/docs/guides/chatchannel/chat_channels_overview' },
  { slug: 'guides-chatchannel-access', group: '指南 · 对话渠道', titleZh: '渠道接入与配置', titleEn: 'Channel Access and Configuration', sourceUrl: 'https://ragflow.io/docs/guides/chatchannel/channel_access_and_configuration' },
  { slug: 'guides-chatchannel-connect', group: '指南 · 对话渠道', titleZh: '连接对话渠道', titleEn: 'Connect Chat', sourceUrl: 'https://ragflow.io/docs/guides/chatchannel/connect_chat' },
  { slug: 'guides-chatchannel-faq', group: '指南 · 对话渠道', titleZh: '对话渠道常见问题', titleEn: 'FAQ', sourceUrl: 'https://ragflow.io/docs/guides/chatchannel/faq' },
  { slug: 'guides-search-create', group: '指南 · 搜索', titleZh: '创建搜索', titleEn: 'Create a Search', sourceUrl: 'https://ragflow.io/docs/guides/search/create_search' },
  { slug: 'guides-search-settings', group: '指南 · 搜索', titleZh: '搜索设置', titleEn: 'Search Settings', sourceUrl: 'https://ragflow.io/docs/guides/search/search_settings' },
  { slug: 'guides-search-faq', group: '指南 · 搜索', titleZh: '搜索常见问题', titleEn: 'FAQ', sourceUrl: 'https://ragflow.io/docs/guides/search/faq' },
  { slug: 'guides-agent-overview', group: '指南 · Agent', titleZh: 'Agent 概览', titleEn: 'Agent Overview', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_overview' },
  { slug: 'guides-agent-creation', group: '指南 · Agent', titleZh: 'Agent 的创建与管理', titleEn: 'Agent Creation and Management', sourceUrl: 'https://ragflow.io/docs/guides/agent/creation_and_management' },
  { slug: 'guides-agent-canvas', group: '指南 · Agent', titleZh: '理解画布', titleEn: 'Understand the Canvas', sourceUrl: 'https://ragflow.io/docs/guides/agent/understand_the_canvas' },
  { slug: 'guides-agent-import-export', group: '指南 · Agent', titleZh: '导入与导出 Agent', titleEn: 'Import and Export Agents', sourceUrl: 'https://ragflow.io/docs/guides/agent/import_and_export_agents' },
  { slug: 'guides-agent-embed', group: '指南 · Agent', titleZh: '嵌入网页', titleEn: 'Embed into Web Pages', sourceUrl: 'https://ragflow.io/docs/guides/agent/embed_into_web_pages' },
  { slug: 'guides-agent-flow-components', group: '指南 · Agent 工作流', titleZh: '流程组件', titleEn: 'Flow Components', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_workflow/flow_components' },
  { slug: 'guides-agent-dialogue', group: '指南 · Agent 工作流', titleZh: '对话组件', titleEn: 'Dialogue Component', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_workflow/dialogue_component' },
  { slug: 'guides-agent-basic-components', group: '指南 · Agent 工作流', titleZh: '基础组件', titleEn: 'Basic Components', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_workflow/basic_component' },
  { slug: 'guides-agent-data-components', group: '指南 · Agent 工作流', titleZh: '数据操作组件', titleEn: 'Data Manipulation Components', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_workflow/data_manipulation_components' },
  { slug: 'guides-agent-tool-components', group: '指南 · Agent 工作流', titleZh: '工具组件', titleEn: 'Tool Components', sourceUrl: 'https://ragflow.io/docs/guides/agent/agent_workflow/tool_components' },
  { slug: 'guides-agent-pipeline-create', group: '指南 · 摄取管道', titleZh: '创建摄取管道', titleEn: 'Create an Ingestion Pipeline', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/create_ingestion_pipeline' },
  { slug: 'guides-agent-pipeline-components', group: '指南 · 摄取管道', titleZh: '理解核心摄取管道组件', titleEn: 'Understand the Core Ingestion Pipeline Components', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/understand_core_ingestion_pipeline_components' },
  { slug: 'guides-agent-pipeline-parser', group: '指南 · 摄取管道', titleZh: '配置解析器组件', titleEn: 'Configure the Parser Component', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/configure_parser_component' },
  { slug: 'guides-agent-pipeline-chunker', group: '指南 · 摄取管道', titleZh: '配置分块器组件', titleEn: 'Configure the Chunker Component', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/configure_chunker_component' },
  { slug: 'guides-agent-pipeline-transformer', group: '指南 · 摄取管道', titleZh: '配置转换器组件', titleEn: 'Configure the Transformer Component', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/configure_transformer_component' },
  { slug: 'guides-agent-pipeline-indexer', group: '指南 · 摄取管道', titleZh: '配置索引器组件', titleEn: 'Configure the Indexer Component', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/configure_indexer_component' },
  { slug: 'guides-agent-pipeline-connect', group: '指南 · 摄取管道', titleZh: '管道接入知识库', titleEn: 'Connect the Pipeline to a Knowledge Base', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/connect_the_pipeline_to_a_knowledge_base' },
  { slug: 'guides-agent-pipeline-test', group: '指南 · 摄取管道', titleZh: '测试运行', titleEn: 'Test Run', sourceUrl: 'https://ragflow.io/docs/guides/agent/ingestion_pipeline/test_run' },
  { slug: 'guides-memory-create', group: '指南 · 记忆', titleZh: '创建记忆', titleEn: 'Create Memory', sourceUrl: 'https://ragflow.io/docs/guides/memory/create_memory' },
  { slug: 'guides-memory-configure', group: '指南 · 记忆', titleZh: '配置记忆', titleEn: 'Configure Memory', sourceUrl: 'https://ragflow.io/docs/guides/memory/configure_memory' },
  { slug: 'guides-memory-connect', group: '指南 · 记忆', titleZh: '连接到 Agent', titleEn: 'Connect to an Agent', sourceUrl: 'https://ragflow.io/docs/guides/memory/connect_to_an_agent' },
  { slug: 'guides-memory-messages', group: '指南 · 记忆', titleZh: '消息页面', titleEn: 'Message Page', sourceUrl: 'https://ragflow.io/docs/guides/memory/message_page' },
  { slug: 'guides-kc-overview', group: '指南 · 知识编译', titleZh: '知识编译概览', titleEn: 'Knowledge Compilation Overview', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/overview' },
  { slug: 'guides-kc-basic-info', group: '指南 · 知识编译', titleZh: '基本信息配置', titleEn: 'Basic Information Configuration', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/basic_information_configuration' },
  { slug: 'guides-kc-runtime', group: '指南 · 知识编译', titleZh: '知识编译运行时配置', titleEn: 'Knowledge Compilation Runtime Configuration', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/runtime_configuration' },
  { slug: 'guides-kc-apply-template', group: '指南 · 知识编译', titleZh: '应用知识编译模板', titleEn: 'Apply a Knowledge Compilation Template', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/apply_knowledge_compilation_template' },
  { slug: 'guides-kc-built-in', group: '指南 · 知识编译', titleZh: '内置模板与专用配置', titleEn: 'Built-in Templates and Dedicated Configuration', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/built_in_templates_and_dedicated_configuration' },
  { slug: 'guides-kc-faq', group: '指南 · 知识编译', titleZh: '知识编译常见问题', titleEn: 'FAQ', sourceUrl: 'https://ragflow.io/docs/guides/knowledge_compilation/faq' },
  { slug: 'guides-models-api-key', group: '指南 · 模型', titleZh: '配置模型 API Key', titleEn: 'Configure Model API Key', sourceUrl: 'https://ragflow.io/docs/guides/models/llm_api_key_setup' },
  { slug: 'guides-models-local', group: '指南 · 模型', titleZh: '本地部署模型', titleEn: 'Deploy Local Models', sourceUrl: 'https://ragflow.io/docs/guides/models/deploy_local_llm' },
  { slug: 'guides-models-supported', group: '指南 · 模型', titleZh: '模型提供商', titleEn: 'Model Providers', sourceUrl: 'https://ragflow.io/docs/guides/models/supported_models' },
  { slug: 'guides-team-permission-index', group: '指南 · 团队', titleZh: '权限系统概览', titleEn: 'Permission System Overview', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview' },
  { slug: 'guides-team-permission-team-resource', group: '指南 · 团队', titleZh: '团队与资源权限', titleEn: 'Team and Resource Permissions', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview/team_and_resource_permissions' },
  { slug: 'guides-team-permission-member', group: '指南 · 团队', titleZh: '团队成员管理', titleEn: 'Team Member Management', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview/team_member_management' },
  { slug: 'guides-team-permission-sharing', group: '指南 · 团队', titleZh: '资源共享范围', titleEn: 'Resource Sharing Scope', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview/resource_sharing_scope' },
  { slug: 'guides-team-permission-operation', group: '指南 · 团队', titleZh: '资源操作权限', titleEn: 'Resource Operation Permissions', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview/resource_operation_permissions' },
  { slug: 'guides-team-permission-rules', group: '指南 · 团队', titleZh: '权限生效规则', titleEn: 'Permission Effective Rules', sourceUrl: 'https://ragflow.io/docs/guides/team/permission_system_overview/permission_effective_rules' },
  { slug: 'guides-team-sharing-index', group: '指南 · 团队', titleZh: '共享范围配置', titleEn: 'Sharing Scope Configuration', sourceUrl: 'https://ragflow.io/docs/guides/team/sharing_scope_configuration' },
  { slug: 'guides-team-sharing-opensource', group: '指南 · 团队', titleZh: '开源版共享范围配置', titleEn: 'Open-source Edition Sharing Scope Configuration', sourceUrl: 'https://ragflow.io/docs/guides/team/sharing_scope_configuration/open_source_edition_sharing_scope_configuration' },
  { slug: 'guides-team-sharing-agents', group: '指南 · 团队', titleZh: '共享 Agent', titleEn: 'Share Agents', sourceUrl: 'https://ragflow.io/docs/guides/team/sharing_scope_configuration/share_agents' },
  { slug: 'guides-team-sharing-kb', group: '指南 · 团队', titleZh: '共享知识库', titleEn: 'Share Knowledge Bases', sourceUrl: 'https://ragflow.io/docs/guides/team/sharing_scope_configuration/share_knowledge_bases' },
  { slug: 'guides-team-sharing-memories', group: '指南 · 团队', titleZh: '共享记忆', titleEn: 'Share Memories', sourceUrl: 'https://ragflow.io/docs/guides/team/sharing_scope_configuration/share_memories' },
  { slug: 'guides-team-mgmt-index', group: '指南 · 团队', titleZh: '团队管理', titleEn: 'Team Management', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management' },
  { slug: 'guides-team-mgmt-enter', group: '指南 · 团队', titleZh: '进入团队页面', titleEn: 'Enter the Team Page', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/enter_the_team_page' },
  { slug: 'guides-team-mgmt-view-members', group: '指南 · 团队', titleZh: '查看当前工作区成员', titleEn: 'View Current Workspace Members', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/view_current_workspace_members' },
  { slug: 'guides-team-mgmt-invite', group: '指南 · 团队', titleZh: '邀请成员', titleEn: 'Invite Members', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/invite_members' },
  { slug: 'guides-team-mgmt-accept', group: '指南 · 团队', titleZh: '接受或拒绝邀请', titleEn: 'Accept or Decline an Invitation', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/accept_or_decline_an_invitation' },
  { slug: 'guides-team-mgmt-remove', group: '指南 · 团队', titleZh: '移除成员', titleEn: 'Remove Members', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/remove_members' },
  { slug: 'guides-team-mgmt-leave', group: '指南 · 团队', titleZh: '退出已加入的团队', titleEn: 'Leave a Joined Team', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/leave_a_joined_team' },
  { slug: 'guides-team-mgmt-view-teams', group: '指南 · 团队', titleZh: '查看已加入的团队', titleEn: 'View Joined Teams', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/view_joined_teams' },
  { slug: 'guides-team-mgmt-share', group: '指南 · 团队', titleZh: '团队视角的资源共享', titleEn: 'Resource Sharing from the Team Perspective', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/resource_sharing_from_the_team_perspective' },
  { slug: 'guides-team-mgmt-faq', group: '指南 · 团队', titleZh: '团队管理常见问题', titleEn: 'FAQ', sourceUrl: 'https://ragflow.io/docs/guides/team/team_management/faq' },
  { slug: 'references-glossary', group: '参考资料', titleZh: '术语表', titleEn: 'Glossary', sourceUrl: 'https://ragflow.io/docs/references/glossary' },
  { slug: 'references-http-api-01', group: '参考资料', titleZh: 'HTTP API 参考（一）', titleEn: 'HTTP API Reference (Part 1)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-02', group: '参考资料', titleZh: 'HTTP API 参考（二）', titleEn: 'HTTP API Reference (Part 2)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-03', group: '参考资料', titleZh: 'HTTP API 参考（三）', titleEn: 'HTTP API Reference (Part 3)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-04', group: '参考资料', titleZh: 'HTTP API 参考（四）', titleEn: 'HTTP API Reference (Part 4)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-05', group: '参考资料', titleZh: 'HTTP API 参考（五）', titleEn: 'HTTP API Reference (Part 5)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-06', group: '参考资料', titleZh: 'HTTP API 参考（六）', titleEn: 'HTTP API Reference (Part 6)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-07', group: '参考资料', titleZh: 'HTTP API 参考（七）', titleEn: 'HTTP API Reference (Part 7)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-08', group: '参考资料', titleZh: 'HTTP API 参考（八）', titleEn: 'HTTP API Reference (Part 8)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-09', group: '参考资料', titleZh: 'HTTP API 参考（九）', titleEn: 'HTTP API Reference (Part 9)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-10', group: '参考资料', titleZh: 'HTTP API 参考（十）', titleEn: 'HTTP API Reference (Part 10)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-http-api-11', group: '参考资料', titleZh: 'HTTP API 参考（十一）', titleEn: 'HTTP API Reference (Part 11)', sourceUrl: 'https://ragflow.io/docs/references/http_api_reference' },
  { slug: 'references-python-api-01', group: '参考资料', titleZh: 'Python API 参考（一）', titleEn: 'Python API Reference (Part 1)', sourceUrl: 'https://ragflow.io/docs/references/python_api_reference' },
  { slug: 'references-python-api-02', group: '参考资料', titleZh: 'Python API 参考（二）', titleEn: 'Python API Reference (Part 2)', sourceUrl: 'https://ragflow.io/docs/references/python_api_reference' },
  { slug: 'references-python-api-03', group: '参考资料', titleZh: 'Python API 参考（三）', titleEn: 'Python API Reference (Part 3)', sourceUrl: 'https://ragflow.io/docs/references/python_api_reference' },
  { slug: 'references-python-api-04', group: '参考资料', titleZh: 'Python API 参考（四）', titleEn: 'Python API Reference (Part 4)', sourceUrl: 'https://ragflow.io/docs/references/python_api_reference' },
  { slug: 'develop-api-key', group: '开发', titleZh: '获取 RAGFlow API Key', titleEn: 'Acquire RAGFlow API Key', sourceUrl: 'https://ragflow.io/docs/develop/acquire_ragflow_api_key' },
  { slug: 'develop-launch-source', group: '开发', titleZh: '从源码启动服务', titleEn: 'Launch Service from Source', sourceUrl: 'https://ragflow.io/docs/develop/launch_ragflow_from_source' },
  { slug: 'develop-build-docker', group: '开发', titleZh: '构建 RAGFlow Docker 镜像', titleEn: 'Build RAGFlow Docker Image', sourceUrl: 'https://ragflow.io/docs/develop/build_docker_image' },
  { slug: 'develop-switch-engine', group: '开发', titleZh: '切换文档引擎', titleEn: 'Switch Document Engine', sourceUrl: 'https://ragflow.io/docs/develop/switch_doc_engine' },
  { slug: 'develop-deepwiki', group: '开发', titleZh: '在 DeepWiki 上探索 RAGFlow', titleEn: 'Explore RAGFlow on DeepWiki', sourceUrl: 'https://ragflow.io/docs/develop/deepwiki' },
  { slug: 'develop-contributing', group: '开发', titleZh: '贡献指南', titleEn: 'Contribution Guidelines', sourceUrl: 'https://ragflow.io/docs/develop/contributing' },
  { slug: 'develop-mcp-server', group: '开发 · MCP', titleZh: '启动 RAGFlow MCP 服务器', titleEn: 'Launch RAGFlow MCP Server', sourceUrl: 'https://ragflow.io/docs/develop/mcp/launch_mcp_server' },
  { slug: 'develop-mcp-tools', group: '开发 · MCP', titleZh: 'RAGFlow MCP 工具', titleEn: 'RAGFlow MCP Tools', sourceUrl: 'https://ragflow.io/docs/develop/mcp/mcp_tools' },
  { slug: 'develop-mcp-client', group: '开发 · MCP', titleZh: 'RAGFlow MCP 客户端示例', titleEn: 'RAGFlow MCP Client Examples', sourceUrl: 'https://ragflow.io/docs/develop/mcp/mcp_client_example' },
  { slug: 'admin-tracing', group: '管理', titleZh: '链路追踪', titleEn: 'Tracing', sourceUrl: 'https://ragflow.io/docs/administrator/tracing' },
  { slug: 'admin-upgrade', group: '管理', titleZh: '升级 RAGFlow', titleEn: 'Upgrade RAGFlow', sourceUrl: 'https://ragflow.io/docs/administrator/upgrade_ragflow' },
  { slug: 'admin-service', group: '管理', titleZh: '管理服务', titleEn: 'Admin Service', sourceUrl: 'https://ragflow.io/docs/administrator/admin/admin_service' },
  { slug: 'admin-cli', group: '管理', titleZh: 'RAGFlow CLI', titleEn: 'RAGFlow CLI', sourceUrl: 'https://ragflow.io/docs/administrator/admin/ragflow_cli' },
  { slug: 'admin-ui-begin', group: '管理 · 后台界面', titleZh: '开始之前', titleEn: 'Before You Begin', sourceUrl: 'https://ragflow.io/docs/administrator/admin/admin_ui/before_you_begin' },
  { slug: 'admin-ui-status', group: '管理 · 后台界面', titleZh: '查看系统状态', titleEn: 'Check System Status', sourceUrl: 'https://ragflow.io/docs/administrator/admin/admin_ui/check_system_status' },
  { slug: 'admin-ui-users', group: '管理 · 后台界面', titleZh: '管理用户账户', titleEn: 'Manage User Accounts', sourceUrl: 'https://ragflow.io/docs/administrator/admin/admin_ui/manage_user_accounts' },
  { slug: 'admin-ui-sandbox', group: '管理 · 后台界面', titleZh: '配置代码执行沙箱', titleEn: 'Configure Code Execution Sandbox', sourceUrl: 'https://ragflow.io/docs/administrator/admin/admin_ui/configure_code_execution_sandbox' },
  { slug: 'admin-config-general', group: '管理 · 配置', titleZh: '系统配置', titleEn: 'Configurations', sourceUrl: 'https://ragflow.io/docs/administrator/configurations/configurations' },
  { slug: 'admin-config-ssl', group: '管理 · 配置', titleZh: '配置 SSL 证书', titleEn: 'Configure SSL Certificates', sourceUrl: 'https://ragflow.io/docs/administrator/configurations/config_ssl_cert' },
  { slug: 'admin-config-sandbox', group: '管理 · 配置', titleZh: '沙箱快速开始', titleEn: 'Sandbox Quickstart', sourceUrl: 'https://ragflow.io/docs/administrator/configurations/sandbox_quickstart' },
  { slug: 'admin-migration-backup', group: '管理 · 迁移', titleZh: '备份与迁移', titleEn: 'Backup and Migration', sourceUrl: 'https://ragflow.io/docs/administrator/migration/backup_and_migration' },
  { slug: 'admin-migration-schema', group: '管理 · 迁移', titleZh: '数据库结构与迁移', titleEn: 'Database Schema and Migration', sourceUrl: 'https://ragflow.io/docs/administrator/migration/database_schema_and_migration' },
  { slug: 'faq', group: '常见问题', titleZh: '常见问题', titleEn: 'FAQ', sourceUrl: 'https://ragflow.io/docs/faq' },
  { slug: 'release-notes-01', group: '更新日志', titleZh: '更新日志（一）', titleEn: 'Releases (Part 1)', sourceUrl: 'https://ragflow.io/docs/release_notes' },
  { slug: 'release-notes-02', group: '更新日志', titleZh: '更新日志（二）', titleEn: 'Releases (Part 2)', sourceUrl: 'https://ragflow.io/docs/release_notes' },
  { slug: 'release-notes-03', group: '更新日志', titleZh: '更新日志（三）', titleEn: 'Releases (Part 3)', sourceUrl: 'https://ragflow.io/docs/release_notes' },
  { slug: 'release-notes-04', group: '更新日志', titleZh: '更新日志（四）', titleEn: 'Releases (Part 4)', sourceUrl: 'https://ragflow.io/docs/release_notes' },
  { slug: 'release-notes-05', group: '更新日志', titleZh: '更新日志（五）', titleEn: 'Releases (Part 5)', sourceUrl: 'https://ragflow.io/docs/release_notes' },
]
